name: Test Unity
on:
  workflow_dispatch: {}
jobs:
  activation:
    name: Test Unity ğŸ–¥ï¸
    runs-on: ubuntu-latest
    steps:
    - name: Unity - Test runner
      uses: game-ci/unity-test-runner@v2.0.2
      with:
        projectPath: pipeline

